# your domain
domain: free-way.herokuapp.com

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  - https://raw.githubusercontent.com/free-gay/free-way/master/config/source.yaml
